name: delivery_food
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

scripts:
  gen: "flutter pub run build_runner watch --delete-conflicting-outputs"
  i18n: "flutter pub run i18n_json"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
  flutter_riverpod: ^2.3.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  firebase_auth: ^4.4.0
  form_builder_validators: ^8.5.0
  auto_route: ^5.0.4
  firebase_messaging: ^14.4.0
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.4
  smooth_page_indicator: ^1.0.1
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_flavorizr: ^2.1.6
  flutter_launcher_icons: ^0.13.0
  i18n_json: ^0.9.1
  auto_route_generator: ^5.0.2
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
    - assets/locales/
    - assets/fonts/
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/app_icons.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Dancing Script
      fonts:
        - asset: assets/fonts/DancingScript-SemiBold.ttf
          weight: 600

flutter_gen:
  output: lib/global/gen
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

flavorizr:
  flavors:
    dev:
      app:
        name: "Delivery Food Dev"

      android:
        applicationId: "com.example.delivery_food"
        firebase:
          config: ".firebase/dev/google-services.json"

      ios:
        bundleId: "com.example.deliveryFood"
        firebase:
          config: ".firebase/dev/GoogleService-Info.plist"

    prod:
      app:
        name: "Delivery Food"

      android:
        applicationId: "com.example.delivery_food"
        firebase:
          config: ".firebase/prod/google-services.json"
      ios:
        bundleId: "com.example.deliveryFood"
        firebase:
          config: ".firebase/prod/GoogleService-Info.plist"
