// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcU4mSQtm679FY7PYXrxy-BRIuXzmmcp4',
    appId: '1:136811929647:web:a60a8debe3a208a6b026da',
    messagingSenderId: '136811929647',
    projectId: 'deliveryfood-bfee4',
    authDomain: 'deliveryfood-bfee4.firebaseapp.com',
    storageBucket: 'deliveryfood-bfee4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmXsncLP4hLeXy4vny_kuxFS1yvdHPqSU',
    appId: '1:136811929647:android:bda2fa4e4b3bec5bb026da',
    messagingSenderId: '136811929647',
    projectId: 'deliveryfood-bfee4',
    storageBucket: 'deliveryfood-bfee4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJagrqlld92JQJwKHYlz_XZsV2--YchMc',
    appId: '1:136811929647:ios:6f799c8ef3315109b026da',
    messagingSenderId: '136811929647',
    projectId: 'deliveryfood-bfee4',
    storageBucket: 'deliveryfood-bfee4.appspot.com',
    iosClientId: '136811929647-peid1m86ur73q2381loac794ed8lj2id.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJagrqlld92JQJwKHYlz_XZsV2--YchMc',
    appId: '1:136811929647:ios:6f799c8ef3315109b026da',
    messagingSenderId: '136811929647',
    projectId: 'deliveryfood-bfee4',
    storageBucket: 'deliveryfood-bfee4.appspot.com',
    iosClientId: '136811929647-peid1m86ur73q2381loac794ed8lj2id.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryFood',
  );
}
